### PR TITLE
Rebar3 master

### PR DESCRIPTION
**Pull request by Juliusan**
I use Yaws on Erlang OTP26 and I also build my projects using rebar3. I know, there is a rebar compatibility branch `rebar3-support`, however, it is too old and doesn't work with OTP26. Moreover, `master` branch of Yaws is updated to OTP26, but it has problems building all C dependencies using rebar3. I've merged these two branches. Please either use this PR to include rebar3 compatibility in `master` branch or make a rebase on `master` of `rebar3-support`.

### CODE REVIEW

**Comment by vinoski** [comment]
Thanks, I'll take a look.

**Comment by vinoski** [comment]
@Juliusan, question: I assume that `rebar3 eunit` still doesn't work with your changes?

**Comment by Juliusan** [comment]
> @Juliusan, question: I assume that `rebar3 eunit` or `rebar3 ct` still don't work with your changes?

"My changes" is saying it too loud :-D I just merged two existing branches and fixed a few merge conflicts, which occurred in make file and documentation.

To answer your question: I use yaws as a dependency and haven't tried running tests on it. But yes, you are right. Both `eunit` and `ct` fail with 'export_all flag enabled - all functions will be exported' in different files.

Shouldn't be hard to fix that, I suppose. And it is supposed to be a warning. I'll have a look.

**Comment by vinoski** [comment]
No need to fix the `export_all` issue, I already have it fixed locally. But there are more problems after fixing that.

I was asking about the `rebar3` commands just so I would know what to expect when reviewing your PR. Thanks for the clarification!

**Comment by vinoski** [comment]
I'm still working on this.

**Comment by vinoski** [comment]
I manually rebased the whole branch and updated it to fix a few things, then merged it to `master` as a single commit. Thanks for pushing this forward!

**Comment by Juliusan** [comment]
Thank you for doing this :-)

**Pull request closed without merging**
